[theme]

# Primary accent for interactive elements
primaryColor = '#fc035a'

# Background color for the main content area
backgroundColor = '#FFFFFF'


# Color used for almost all text
textColor = '#000000'
